version: "3.9"
services:
  server-prod:
    image: "da-nang-internship-docker-local.dockerregistry.mgm-tp.com/com.mgmtp.da-nang-internship/com.mgmtp.cfu.server:master"
    container_name: "server-prod"
    env_file:
      - .env.master
    profiles: [ 'production' ]
    ports:
      - "8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - spring.web.resources.static-locations=file:/app/uploads
      - course4u.upload.thumbnail-directory=./uploads/api/thumbnail
    networks:
      - "cfu"
    labels:
      - "traefik.http.routers.cfu-server-prod.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.cfu-server-prod-api-middleware.replacepathregex.regex=^/api/(.*)"
      - "traefik.http.middlewares.cfu-server-prod-api-middleware.replacepathregex.replacement=/api/$$1"
      - "traefik.http.routers.cfu-server-prod-cfu.middlewares=cfu-server-prod-api-middleware"

  client-prod:
    image: "da-nang-internship-docker-local.dockerregistry.mgm-tp.com/com.mgmtp.da-nang-internship/com.mgmtp.cfu.client:master"
    container_name: "client-prod"
    profiles: [ 'production' ]
    ports:
      - "80"
    networks:
      - "cfu"
    depends_on:
      - "server-prod"
    labels:
      - "traefik.http.routers.cfu-client-prod-cfu.rule=PathPrefix(`/`)"
      - "traefik.http.middlewares.cfu-client-prod-middleware.replacepathregex.regex=^(.*)"
      - "traefik.http.middlewares.cfu-client-prod-middleware.replacepathregex.replacement=$$1"
      - "traefik.http.routers.cfu-client-prod-cfu.middlewares=cfu-client-prod-middleware"
networks:
  cfu:
    external: true
    name: cfu