version: "3.9"
services:
  server-staging:
    image: "da-nang-internship-docker-local.dockerregistry.mgm-tp.com/com.mgmtp.da-nang-internship/com.mgmtp.cfu.server:staging"
    container_name: "server-staging"
    env_file:
      - .env.staging
    profiles: [ 'staging' ]
    ports:
      - "8080"
    networks:
      - "cfu"
    labels:
      - "traefik.http.routers.cfu-server-staging-cfu.rule=PathPrefix(`/staging/api`)"
      - "traefik.http.middlewares.cfu-server-staging-middleware.replacepathregex.regex=^/staging/api/(.*)"
      - "traefik.http.middlewares.cfu-server-staging-middleware.replacepathregex.replacement=/api/$$1"
      - "traefik.http.routers.cfu-server-staging-cfu.middlewares=cfu-server-staging-middleware"

  client-staging:
    image: "da-nang-internship-docker-local.dockerregistry.mgm-tp.com/com.mgmtp.da-nang-internship/com.mgmtp.cfu.client:staging"
    container_name: "client-staging"
    profiles: [ 'staging' ]
    ports:
      - "80"
    networks:
      - "cfu"
    depends_on:
      - "server-staging"
    labels:
      - "traefik.http.routers.cfu-client-staging-cfu.rule=PathPrefix(`/staging`)"
      - "traefik.http.middlewares.cfu-client-staging-middleware.replacepathregex.regex=^/staging(.*)"
      - "traefik.http.middlewares.cfu-client-staging-middleware.replacepathregex.replacement=$$1"
      - "traefik.http.routers.cfu-client-staging-cfu.middlewares=cfu-client-staging-middleware"

networks:
  cfu:
    external: true
    name: cfu