name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Give permission for gradlew
        run: chmod +x server/gradlew

      - name: Build and test server
        run: ./gradlew build
        working-directory: server

  build-client:
    runs-on: ubuntu-latest
    needs: build-and-test-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build client
        run: |
          BUILD_MODE=:develop
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            BUILD_MODE=:staging
          elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
            BUILD_MODE=:master
          fi
          npm ci && npm run build${BUILD_MODE}
        working-directory: client

  build-and-publish-images:
    runs-on: ubuntu-latest
    needs: build-client
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client image
        run: |
          VERSION=${{ github.ref_name }}
          docker build . -t duycan17/course4u.client:${VERSION}
          docker push duycan17/course4u.client:${VERSION}
        working-directory: client

      - name: Build and push server image
        run: |
          VERSION=${{ github.ref_name }}
          docker build . -t duycan17/course4u.server:${VERSION}
          docker push duycan17/course4u.server:${VERSION}
        working-directory: server

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish-images
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose.yaml to remote server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: 103.173.66.200
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 8686
          source: './docker-compose.yaml'
          target: '/home/cfu'

      - name: SSH to remote server and deploy
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: 103.173.66.200
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 8686
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            PROFILE=develop
            if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
              PROFILE=staging
            elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
              PROFILE=production
            fi
            docker compose --project-name cfu --profile ${PROFILE} up -d --pull=always
            docker logout